# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://docs.astral.sh/ruff/
name: codespell_and_ruff
on:
  push:
    branches: [master, patches]
  pull_request:
    branches: [master, patches]
jobs:
  codespell_and_ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: pip install --user codespell[toml] ruff
    - run: codespell --ignore-words-list=mathes,millon,ned --skip="*.csv,*.rss"
    - run: ruff --output-format=github --ignore=E401,E402,E701,E712,E713,E721,E722,E731,E741,F401,F403,F405,F811,F821,F841
                --exclude=doc/docstring.py,doc/conf.py,scripts/mkrelease.py,scripts/mkwiki.py,scripts/mkindex.py,examples/attrib_plugin.py

