name: legacy_python

on:
  push:
  pull_request:

jobs:
  legacy_python:
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.3"
            os: "ubuntu-18.04"
          - python-version: "3.4"
            os: "ubuntu-18.04"
          - python-version: "3.5"
            os: "ubuntu-20.04"
          - python-version: "3.6"
            os: "ubuntu-20.04"
          - python-version: "3.7"
            os: "ubuntu-22.04"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: python -m pip install tox==2.9.1 virtualenv==15.2.0
      - run: tox -e py
